In [1]:
N = ord('K') % 15 + 1
N

1

# Вправа 1. Вводиться число n. Вивести масив разміра nхn, в якому по діагоналі йдуть числа від 1 до n, а інші числа рівні 0

In [2]:
%%time
n = int(input())
matrix = [[0 for j in range(n)] for i in range(n)]

for i in range(n):
    matrix[i][i] = i + 1

for row in matrix:
    for element in row:
        print(element, end=" ")
    print()

4
1 0 0 0 
0 2 0 0 
0 0 3 0 
0 0 0 4 
CPU times: total: 46.9 ms
Wall time: 1.51 s


In [3]:
%%time
import numpy as np

n = int(input())
a1 = np.zeros((n, n), dtype=int)

for i in range(n):
    a1[i, i] = i+1
a1

4
CPU times: total: 156 ms
Wall time: 1.45 s


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Вправа 6. З клавіатури вводиться масив. Замінити всі ненульові елементи на -1.

In [4]:
%%time
n = int(input())
task_6 = []

for i in range(n):
    element = int(input(f"{i+1} element: "))
    task_6.append(element)
print(task_6)

for i in range(n):
    if task_6[i] != 0:
        task_6[i] = -1
task_6

5
1 element: 1
2 element: 2
3 element: 3
4 element: 4
5 element: 0
[1, 2, 3, 4, 0]
CPU times: total: 46.9 ms
Wall time: 8.36 s


[-1, -1, -1, -1, 0]

In [5]:
%%time
n = int(input())
task_6_2 = np.arange(n, dtype = int)

for i in range(n):
    task_6_2[i] = int(input(f"{i+1} element: "))
print(task_6_2)
task_6_2[task_6_2 != 0] = -1
task_6_2

5
1 element: 1
2 element: 2
3 element: 3
4 element: 4
5 element: 0
[1 2 3 4 0]
CPU times: total: 15.6 ms
Wall time: 5 s


array([-1, -1, -1, -1,  0])

# Вправа 7. З клавіатури вводиться масив. Замінити всі нульові елементи на -1.

In [6]:
%%time
n = int(input())
task_7 = []

for i in range(n):
    element = int(input(f"{i+1} element: "))
    task_7.append(element)
print(task_7)

for i in range(n):
    if task_7[i] == 0:
        task_7[i] = -1
task_7

4
1 element: 1
2 element: 2
3 element: 0
4 element: 0
[1, 2, 0, 0]
CPU times: total: 15.6 ms
Wall time: 4.16 s


[1, 2, -1, -1]

In [7]:
%%time
n = int(input())
task_7_2 = np.arange(n, dtype = int)

for i in range(n):
    task_7_2[i] = int(input(f"{i+1} element: "))
print(task_7_2)
task_7_2[task_7_2 == 0] = -1
task_7_2

4
1 element: 1
2 element: 2
3 element: 0
4 element: 0
[1 2 0 0]
CPU times: total: 0 ns
Wall time: 2.97 s


array([ 1,  2, -1, -1])

# Вправа 9. Вводиться число n. Створити масив значень від n до 0.

In [8]:
%%time
n = int(input())
task_9 = list(range(n,-1,-1))
task_9

5
CPU times: total: 0 ns
Wall time: 1.08 s


[5, 4, 3, 2, 1, 0]

In [9]:
%%time
n = int(input())
task_9_2 = np.arange(n+1, dtype=int)
for i in range(n+1):
   task_9_2[i] = n-i
task_9_2

5
CPU times: total: 0 ns
Wall time: 861 ms


array([5, 4, 3, 2, 1, 0])

# Вправа 10. Вводиться числа n i m. Створити масив випадкових значень n на m і обчислити мінімальне, максимальне значення, середнє та середньо квадратичне відхилення, округлене до 3 знаків після коми

In [10]:
%%time
import random

n = int(input("n: "))
m = int(input("m: "))

task_10 = [[random.randint(0,100) for j in range(m)] for i in range(n)]

min_val = task_10[0][0]
max_val = task_10[0][0]
sum_val = 0
sum_sq_val = 0

for i in range(n):
    for j in range(m):
        if task_10[i][j] < min_val:
            min_val = task_10[i][j]
        if task_10[i][j] > max_val:
            max_val = task_10[i][j]
        sum_val += task_10[i][j]
        sum_sq_val += task_10[i][j] ** 2

mean_val = sum_val / (n * m)
std_val = ((sum_sq_val / (n * m)) - (mean_val ** 2)) ** 0.5

print(task_10)

print("minimum value:", min_val)
print("maximum value:", max_val)
print("mean value:", round(mean_val, 3))
print("standard deviation:", round(std_val, 3))

n: 5
m: 6
[[65, 74, 87, 76, 28, 17], [55, 74, 12, 77, 24, 4], [6, 83, 91, 41, 91, 27], [44, 72, 76, 9, 18, 45], [9, 99, 73, 59, 68, 38]]
minimum value: 4
maximum value: 99
mean value: 51.4
standard deviation: 29.444
CPU times: total: 15.6 ms
Wall time: 1.63 s


In [11]:
%%time
n = int(input("n: "))
m = int(input("m: "))

task_10_2 = np.random.randint(low=0, high=101, size=(n, m))
min_val = task_10_2.min()
max_val = task_10_2.max()
mean_val = task_10_2.mean()
std_val = task_10_2.std()

print(task_10_2)

print("Minimum value:", min_val)
print("Maximum value:", max_val)
print("Mean value:", round(mean_val, 3))
print("Standard deviation:", round(std_val, 3))

n: 5
m: 6
[[ 1 29 46  5 85 23]
 [78 27 32 87 63 54]
 [71 74 38 43 51 56]
 [18 49 93 15 97 68]
 [48 11 37 38 19 19]]
Minimum value: 1
Maximum value: 97
Mean value: 45.833
Standard deviation: 26.549
CPU times: total: 15.6 ms
Wall time: 1.22 s


# Вправа 11. Створити масив одиниць розміром n х n та додати до нього «рамку», сформовану з 0.

In [12]:
%%time
n = int(input())
task_11 = [[1] * n for i in range(n)]
task_11 = [[0] * (n+2)] + [[0] + row + [0] for row in task_11] + [[0] * (n+2)]
for row in task_11:
    print(row)

4
[0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 0, 0, 0, 0, 0]
CPU times: total: 0 ns
Wall time: 833 ms


In [13]:
%%time
n = int(input())
task_11 = np.ones((n, n), dtype=int)
task_11 = np.pad(task_11, ((1, 1), (1, 1)), mode='constant', constant_values=0)
print(task_11)

4
[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]
CPU times: total: 31.2 ms
Wall time: 621 ms


# Вправа 15. Заповнити парні стовбчики матриці розміром n х n одиницями, а непарні – нулями.

In [14]:
%%time

n = int(input("n: "))

task_15 = [[1] * n for i in range(n)]
for i in range(n):
    for j in range(n):
        if j%2==0:
            task_15[i][j] = 0
for row in task_15:
    print(row)

n: 5
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
CPU times: total: 0 ns
Wall time: 1.73 s


In [15]:
%%time
n = int(input("n: "))
task_15_2 = np.zeros((n,n), dtype = int)

for i in range(n):
    for j in range(n):
        if j%2 != 0:
            task_15_2[i][j] = 1
task_15_2

n: 5
CPU times: total: 0 ns
Wall time: 1.77 s


array([[0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0]])

# Вправа 17. Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значеннь, що менші за n/2 та більші за 3n/4 на протилежні

In [16]:
%%time
n = int(input())
task_17 = []

for i in range(n):
    element = int(input(f"{i+1} element: "))
    task_17.append(element)
print(task_17)

for i in range(n):
    if (task_17[i] < n/2) or (task_17[i] > 3*n/4):
        task_17[i] = -task_17[i]
task_17

5
1 element: 1
2 element: 2
3 element: 3
4 element: 4
5 element: 5
[1, 2, 3, 4, 5]
CPU times: total: 0 ns
Wall time: 4.15 s


[-1, -2, 3, -4, -5]

In [17]:
%%time
n = int(input())
task_17_2 = np.arange(n, dtype = int)

for i in range(n):
    task_17_2[i] = int(input(f"{i+1} element: "))
print(task_17_2)

task_17_2[(task_17_2 < n/2) | (task_17_2 > 3*n/4)] *= -1
task_17_2

5
1 element: 1
2 element: 2
3 element: 3
4 element: 4
5 element: 5
[1 2 3 4 5]
CPU times: total: 46.9 ms
Wall time: 3.88 s


array([-1, -2,  3, -4, -5])

# Вправа 18. Згенерувати вектор з n випадкових чисел в діапазоні від 0 до 99. Визначити кількість унікальних чисел в послідовності.

In [18]:
%%time

n = int(input("n: "))
task_18 = [random.randint(0,99) for j in range(n)]
print(task_18)

sum_count = 0
for i in range(n):
    com_count = 0
    for j in range(n):
        if task_18[i] == task_18[j]:
            com_count += 1
    if com_count == 1:
        sum_count += 1
sum_count

n: 30
[71, 75, 65, 89, 79, 69, 13, 39, 5, 65, 17, 23, 26, 58, 24, 20, 22, 56, 10, 74, 47, 48, 67, 67, 44, 53, 13, 3, 54, 30]
CPU times: total: 15.6 ms
Wall time: 1.09 s


24

In [19]:
%%time
n = int(input("n: "))
task_18_2 = np.random.randint(0, 100, n)
print(task_18_2)
unique, count = np.unique(task_18_2, return_counts=True)
print("Number of unique elements:", len(unique))

n: 30
[29 45 58  8 20 68 57 54  0 22 39 90 73 39 31 13 43 68 56 23 90 96 62  4
 75 64 46  7 64 36]
Number of unique elements: 26
CPU times: total: 0 ns
Wall time: 3.07 s


$$
2) \begin{cases}
x_1 + x_2 + 2x_3 + 3x_4 = 1 \\
3x_1 - x_2 - x_3 - 2x_4 = -4 \\
2x_1 - 3x_2 - x_3 - x_4 = -6 \\
x_1 + 2x_2 + 3x_3 - x_4 = -4
\end{cases}
$$

In [20]:
import numpy as np

A = np.array([[1, 1, 2, 3], [3, -1, -1, -2], [2, -3, -1, -1], [1, 2, 3, -1]])
b = np.array([1, -4, -6, -4])

detA = np.linalg.det(A)

det1 = np.linalg.det(np.column_stack((b, A[:, 1:],)))
det2 = np.linalg.det(np.column_stack((A[:, 0], b, A[:, 2:],)))
det3 = np.linalg.det(np.column_stack((A[:, :2], b, A[:, 3:],)))
det4 = np.linalg.det(np.column_stack((A[:, :3], b)))

x1 = det1 / detA
x2 = det2 / detA
x3 = det3 / detA
x4 = det4 / detA

x = np.array([x1, x2, x3, x4])


res1 = np.dot(A, x)
print(np.allclose(res1, b))


A_inv = np.linalg.inv(A)
res2 = np.dot(A_inv, b)
print(np.allclose(res2, x))


res3 = np.linalg.solve(A, b)
print(np.allclose(res3, x))

True
True
True


$$ 3) 2(A+B)(2B-A), де \quad A = \begin{pmatrix} 2 & 3 & -1 \\ 4 & 5 & 2 \\ -1 & 0 & 7 \end{pmatrix}, \quad B = \begin{pmatrix} -1 & 0 & 5 \\ 0 & 1 & 3 \\ 2 & -2 & 4 \end{pmatrix}$$

In [21]:
%%time

A = np.array([[2, 3, -1], [4, 5, 2], [-1, 0, 7]])
B = np.array([[-1, 0, 5], [0, 1, 3], [2, -2, 4]])

result = 2 * np.dot(A+B, 2*B-A)
print(result)

[[   8  -56   54]
 [ -30 -100  146]
 [ 118  -82   28]]
CPU times: total: 0 ns
Wall time: 999 µs


In [22]:
%%time
A = [[2, 3, -1], [4, 5, 2], [-1, 0, 7]]
B = [[-1, 0, 5], [0, 1, 3], [2, -2, 4]]

result = []
for i in range(3):
    row = []
    for j in range(3):
        s = 0
        for k in range(3):
            s += (A[i][k] + B[i][k]) * (2*B[k][j] - A[k][j])
        row.append(s * 2)
    result.append(row)

print(result)

[[8, -56, 54], [-30, -100, 146], [118, -82, 28]]
CPU times: total: 0 ns
Wall time: 0 ns


Висновок: в ході виконання цієї лабораторної роботи було визначено, що при правильному використанні бібліотеки Numpy виконання коду може суттєво прискоритись.

Посилання на GitHub: https://github.com/ksks48/Python-labs.git